// Code generated by mockery v2.53.6. DO NOT EDIT.

package fraud_log

import (
	dto "github.com/alex/ads_backend/internal/core/fraud_log/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// Create provides a mock function with given fields: input
func (_m *MockService) Create(input dto.CreateFraudLogInput) (*FraudLog, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *FraudLog
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.CreateFraudLogInput) (*FraudLog, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(dto.CreateFraudLogInput) *FraudLog); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*FraudLog)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.CreateFraudLogInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExistsOpenDuplicate provides a mock function with given fields: creativeID, eventType, newValue
func (_m *MockService) ExistsOpenDuplicate(creativeID string, eventType string, newValue string) (bool, error) {
	ret := _m.Called(creativeID, eventType, newValue)

	if len(ret) == 0 {
		panic("no return value specified for ExistsOpenDuplicate")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (bool, error)); ok {
		return rf(creativeID, eventType, newValue)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(creativeID, eventType, newValue)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(creativeID, eventType, newValue)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: filter
func (_m *MockService) FindAll(filter dto.FraudLogFilter) ([]dto.FraudLogResponse, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []dto.FraudLogResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(dto.FraudLogFilter) ([]dto.FraudLogResponse, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(dto.FraudLogFilter) []dto.FraudLogResponse); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.FraudLogResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.FraudLogFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(dto.FraudLogFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: id
func (_m *MockService) FindByID(id uint64) (dto.FraudLogResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 dto.FraudLogResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (dto.FraudLogResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint64) dto.FraudLogResponse); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(dto.FraudLogResponse)
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Resolve provides a mock function with given fields: id, userID
func (_m *MockService) Resolve(id uint64, userID uint64) (dto.FraudLogResponse, error) {
	ret := _m.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 dto.FraudLogResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, uint64) (dto.FraudLogResponse, error)); ok {
		return rf(id, userID)
	}
	if rf, ok := ret.Get(0).(func(uint64, uint64) dto.FraudLogResponse); ok {
		r0 = rf(id, userID)
	} else {
		r0 = ret.Get(0).(dto.FraudLogResponse)
	}

	if rf, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = rf(id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
