// Code generated by mockery v2.53.6. DO NOT EDIT.

package brand

import (
	dto "github.com/alex/ads_backend/internal/core/brand/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: brand
func (_m *MockRepository) Create(brand *Brand) error {
	ret := _m.Called(brand)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*Brand) error); ok {
		r0 = rf(brand)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *MockRepository) Delete(id uint64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: filter
func (_m *MockRepository) FindAll(filter dto.BrandFilter) ([]Brand, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []Brand
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(dto.BrandFilter) ([]Brand, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(dto.BrandFilter) []Brand); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Brand)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.BrandFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(dto.BrandFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: id
func (_m *MockRepository) FindByID(id uint64) (*Brand, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *Brand
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*Brand, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint64) *Brand); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Brand)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: brand
func (_m *MockRepository) Update(brand *Brand) error {
	ret := _m.Called(brand)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*Brand) error); ok {
		r0 = rf(brand)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
