// Code generated by mockery v2.53.6. DO NOT EDIT.

package brand

import (
	dto "github.com/alex/ads_backend/internal/core/brand/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// Create provides a mock function with given fields: req
func (_m *MockService) Create(req dto.CreateBrandRequest) (dto.BrandResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 dto.BrandResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.CreateBrandRequest) (dto.BrandResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(dto.CreateBrandRequest) dto.BrandResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(dto.BrandResponse)
	}

	if rf, ok := ret.Get(1).(func(dto.CreateBrandRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: slug
func (_m *MockService) Delete(slug string) error {
	ret := _m.Called(slug)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: filter
func (_m *MockService) FindAll(filter dto.BrandFilter) ([]dto.BrandResponse, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []dto.BrandResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(dto.BrandFilter) ([]dto.BrandResponse, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(dto.BrandFilter) []dto.BrandResponse); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.BrandResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.BrandFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(dto.BrandFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindBySlug provides a mock function with given fields: slug
func (_m *MockService) FindBySlug(slug string) (dto.BrandResponse, error) {
	ret := _m.Called(slug)

	if len(ret) == 0 {
		panic("no return value specified for FindBySlug")
	}

	var r0 dto.BrandResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (dto.BrandResponse, error)); ok {
		return rf(slug)
	}
	if rf, ok := ret.Get(0).(func(string) dto.BrandResponse); ok {
		r0 = rf(slug)
	} else {
		r0 = ret.Get(0).(dto.BrandResponse)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: slug, req
func (_m *MockService) Update(slug string, req dto.UpdateBrandRequest) (dto.BrandResponse, error) {
	ret := _m.Called(slug, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dto.BrandResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, dto.UpdateBrandRequest) (dto.BrandResponse, error)); ok {
		return rf(slug, req)
	}
	if rf, ok := ret.Get(0).(func(string, dto.UpdateBrandRequest) dto.BrandResponse); ok {
		r0 = rf(slug, req)
	} else {
		r0 = ret.Get(0).(dto.BrandResponse)
	}

	if rf, ok := ret.Get(1).(func(string, dto.UpdateBrandRequest) error); ok {
		r1 = rf(slug, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
