// Code generated by mockery v2.53.6. DO NOT EDIT.

package dashboard

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDashboardRepository is an autogenerated mock type for the DashboardRepository type
type MockDashboardRepository struct {
	mock.Mock
}

// GetBrandsMonitoring provides a mock function with given fields: ctx, startDate, endDate
func (_m *MockDashboardRepository) GetBrandsMonitoring(ctx context.Context, startDate string, endDate string) ([]BrandMonitoringItemRaw, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetBrandsMonitoring")
	}

	var r0 []BrandMonitoringItemRaw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]BrandMonitoringItemRaw, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []BrandMonitoringItemRaw); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BrandMonitoringItemRaw)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecentActivities provides a mock function with given fields: ctx, startDate, endDate
func (_m *MockDashboardRepository) GetRecentActivities(ctx context.Context, startDate string, endDate string) ([]RecentActivityItemRaw, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentActivities")
	}

	var r0 []RecentActivityItemRaw
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]RecentActivityItemRaw, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []RecentActivityItemRaw); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]RecentActivityItemRaw)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSummaryMetrics provides a mock function with given fields: ctx, startDate, endDate
func (_m *MockDashboardRepository) GetSummaryMetrics(ctx context.Context, startDate string, endDate string) (float64, int64, int64, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetSummaryMetrics")
	}

	var r0 float64
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (float64, int64, int64, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) float64); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) int64); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) int64); ok {
		r2 = rf(ctx, startDate, endDate)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string) error); ok {
		r3 = rf(ctx, startDate, endDate)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// NewMockDashboardRepository creates a new instance of MockDashboardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDashboardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDashboardRepository {
	mock := &MockDashboardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
