// Code generated by mockery v2.53.6. DO NOT EDIT.

package dashboard

import (
	context "context"

	dto "github.com/alex/ads_backend/internal/reporting/dashboard/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockDashboardService is an autogenerated mock type for the DashboardService type
type MockDashboardService struct {
	mock.Mock
}

// GetBrandsMonitoring provides a mock function with given fields: ctx, startDate, endDate
func (_m *MockDashboardService) GetBrandsMonitoring(ctx context.Context, startDate string, endDate string) ([]dto.BrandMonitoringItem, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetBrandsMonitoring")
	}

	var r0 []dto.BrandMonitoringItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]dto.BrandMonitoringItem, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []dto.BrandMonitoringItem); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.BrandMonitoringItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecentActivities provides a mock function with given fields: ctx, startDate, endDate
func (_m *MockDashboardService) GetRecentActivities(ctx context.Context, startDate string, endDate string) ([]dto.RecentActivityItem, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentActivities")
	}

	var r0 []dto.RecentActivityItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]dto.RecentActivityItem, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []dto.RecentActivityItem); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.RecentActivityItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSummary provides a mock function with given fields: ctx, startDate, endDate
func (_m *MockDashboardService) GetSummary(ctx context.Context, startDate string, endDate string) (*dto.SummaryResponse, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetSummary")
	}

	var r0 *dto.SummaryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*dto.SummaryResponse, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dto.SummaryResponse); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SummaryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockDashboardService creates a new instance of MockDashboardService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDashboardService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDashboardService {
	mock := &MockDashboardService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
