// Code generated by mockery v2.53.6. DO NOT EDIT.

package sync

import (
	context "context"

	dto "github.com/alex/ads_backend/internal/meta/sync/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockJobTrigger is an autogenerated mock type for the JobTrigger type
type MockJobTrigger struct {
	mock.Mock
}

// IsRunning provides a mock function with no fields
func (_m *MockJobTrigger) IsRunning() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRunning")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Start provides a mock function with given fields: ctx, req
func (_m *MockJobTrigger) Start(ctx context.Context, req dto.TriggerSyncRequest) ([]*MetaSyncBatch, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 []*MetaSyncBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.TriggerSyncRequest) ([]*MetaSyncBatch, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.TriggerSyncRequest) []*MetaSyncBatch); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*MetaSyncBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.TriggerSyncRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockJobTrigger creates a new instance of MockJobTrigger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobTrigger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobTrigger {
	mock := &MockJobTrigger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
