// Code generated by mockery v2.53.6. DO NOT EDIT.

package contact_person

import (
	dto "github.com/alex/ads_backend/internal/core/contact_person/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// Create provides a mock function with given fields: req
func (_m *MockService) Create(req dto.ContactPersonRequest) (*dto.ContactPersonResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.ContactPersonResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.ContactPersonRequest) (*dto.ContactPersonResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(dto.ContactPersonRequest) *dto.ContactPersonResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ContactPersonResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.ContactPersonRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *MockService) Delete(id uint64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: limit, offset
func (_m *MockService) FindAll(limit int, offset int) ([]dto.ContactPersonListResponse, int64, error) {
	ret := _m.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []dto.ContactPersonListResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]dto.ContactPersonListResponse, int64, error)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int) []dto.ContactPersonListResponse); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ContactPersonListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: id
func (_m *MockService) FindByID(id uint64) (*dto.ContactPersonResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *dto.ContactPersonResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*dto.ContactPersonResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint64) *dto.ContactPersonResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ContactPersonResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, req
func (_m *MockService) Update(id uint64, req dto.ContactPersonRequest) (*dto.ContactPersonResponse, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *dto.ContactPersonResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, dto.ContactPersonRequest) (*dto.ContactPersonResponse, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(uint64, dto.ContactPersonRequest) *dto.ContactPersonResponse); ok {
		r0 = rf(id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ContactPersonResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, dto.ContactPersonRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
