// Code generated by mockery v2.53.6. DO NOT EDIT.

package campaign

import (
	dto "github.com/alex/ads_backend/internal/meta/campaign/dto"
	mock "github.com/stretchr/testify/mock"

	response "github.com/alex/ads_backend/pkg/response"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// GetCampaignByID provides a mock function with given fields: id
func (_m *MockService) GetCampaignByID(id string) (*dto.CampaignResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaignByID")
	}

	var r0 *dto.CampaignResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*dto.CampaignResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *dto.CampaignResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CampaignResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCampaignDashboard provides a mock function with given fields: filter
func (_m *MockService) GetCampaignDashboard(filter CampaignFilter) ([]dto.CampaignDashboardRow, *response.PaginationMeta, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaignDashboard")
	}

	var r0 []dto.CampaignDashboardRow
	var r1 *response.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(CampaignFilter) ([]dto.CampaignDashboardRow, *response.PaginationMeta, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(CampaignFilter) []dto.CampaignDashboardRow); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.CampaignDashboardRow)
		}
	}

	if rf, ok := ret.Get(1).(func(CampaignFilter) *response.PaginationMeta); ok {
		r1 = rf(filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.PaginationMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(CampaignFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetCampaignListByBrand provides a mock function with given fields: brandID
func (_m *MockService) GetCampaignListByBrand(brandID uint64) ([]dto.SimpleListResponse, error) {
	ret := _m.Called(brandID)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaignListByBrand")
	}

	var r0 []dto.SimpleListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) ([]dto.SimpleListResponse, error)); ok {
		return rf(brandID)
	}
	if rf, ok := ret.Get(0).(func(uint64) []dto.SimpleListResponse); ok {
		r0 = rf(brandID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.SimpleListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(brandID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCampaigns provides a mock function with given fields: filter
func (_m *MockService) GetCampaigns(filter CampaignFilter) ([]dto.CampaignResponse, *response.PaginationMeta, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaigns")
	}

	var r0 []dto.CampaignResponse
	var r1 *response.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(CampaignFilter) ([]dto.CampaignResponse, *response.PaginationMeta, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(CampaignFilter) []dto.CampaignResponse); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.CampaignResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(CampaignFilter) *response.PaginationMeta); ok {
		r1 = rf(filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.PaginationMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(CampaignFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetSummaryByBrand provides a mock function with given fields: brandID, dateStart, dateStop
func (_m *MockService) GetSummaryByBrand(brandID uint64, dateStart string, dateStop string) (*dto.CampaignSummaryResponse, error) {
	ret := _m.Called(brandID, dateStart, dateStop)

	if len(ret) == 0 {
		panic("no return value specified for GetSummaryByBrand")
	}

	var r0 *dto.CampaignSummaryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, string, string) (*dto.CampaignSummaryResponse, error)); ok {
		return rf(brandID, dateStart, dateStop)
	}
	if rf, ok := ret.Get(0).(func(uint64, string, string) *dto.CampaignSummaryResponse); ok {
		r0 = rf(brandID, dateStart, dateStop)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CampaignSummaryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, string, string) error); ok {
		r1 = rf(brandID, dateStart, dateStop)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SyncCampaigns provides a mock function with given fields: adAccountID
func (_m *MockService) SyncCampaigns(adAccountID string) (int, error) {
	ret := _m.Called(adAccountID)

	if len(ret) == 0 {
		panic("no return value specified for SyncCampaigns")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(adAccountID)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(adAccountID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(adAccountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SyncCampaignsByIDs provides a mock function with given fields: adAccountID, ids
func (_m *MockService) SyncCampaignsByIDs(adAccountID string, ids []string) (int, error) {
	ret := _m.Called(adAccountID, ids)

	if len(ret) == 0 {
		panic("no return value specified for SyncCampaignsByIDs")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []string) (int, error)); ok {
		return rf(adAccountID, ids)
	}
	if rf, ok := ret.Get(0).(func(string, []string) int); ok {
		r0 = rf(adAccountID, ids)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = rf(adAccountID, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
