// Code generated by mockery v2.53.6. DO NOT EDIT.

package campaign

import (
	dto "github.com/alex/ads_backend/internal/meta/campaign/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: filter
func (_m *MockRepository) FindAll(filter CampaignFilter) ([]MetaCampaign, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []MetaCampaign
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(CampaignFilter) ([]MetaCampaign, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(CampaignFilter) []MetaCampaign); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MetaCampaign)
		}
	}

	if rf, ok := ret.Get(1).(func(CampaignFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(CampaignFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: id
func (_m *MockRepository) FindByID(id string) (*MetaCampaign, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *MetaCampaign
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*MetaCampaign, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *MetaCampaign); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MetaCampaign)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindCampaignDashboard provides a mock function with given fields: filter
func (_m *MockRepository) FindCampaignDashboard(filter CampaignFilter) ([]campaignDashboardScan, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindCampaignDashboard")
	}

	var r0 []campaignDashboardScan
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(CampaignFilter) ([]campaignDashboardScan, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(CampaignFilter) []campaignDashboardScan); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]campaignDashboardScan)
		}
	}

	if rf, ok := ret.Get(1).(func(CampaignFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(CampaignFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindSimpleListByBrand provides a mock function with given fields: brandID
func (_m *MockRepository) FindSimpleListByBrand(brandID uint64) ([]dto.SimpleListResponse, error) {
	ret := _m.Called(brandID)

	if len(ret) == 0 {
		panic("no return value specified for FindSimpleListByBrand")
	}

	var r0 []dto.SimpleListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) ([]dto.SimpleListResponse, error)); ok {
		return rf(brandID)
	}
	if rf, ok := ret.Get(0).(func(uint64) []dto.SimpleListResponse); ok {
		r0 = rf(brandID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.SimpleListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(brandID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSummaryByBrand provides a mock function with given fields: brandID, dateStart, dateStop
func (_m *MockRepository) GetSummaryByBrand(brandID uint64, dateStart string, dateStop string) ([]InsightSummaryRow, error) {
	ret := _m.Called(brandID, dateStart, dateStop)

	if len(ret) == 0 {
		panic("no return value specified for GetSummaryByBrand")
	}

	var r0 []InsightSummaryRow
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, string, string) ([]InsightSummaryRow, error)); ok {
		return rf(brandID, dateStart, dateStop)
	}
	if rf, ok := ret.Get(0).(func(uint64, string, string) []InsightSummaryRow); ok {
		r0 = rf(brandID, dateStart, dateStop)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]InsightSummaryRow)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, string, string) error); ok {
		r1 = rf(brandID, dateStart, dateStop)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: campaign
func (_m *MockRepository) Upsert(campaign *MetaCampaign) error {
	ret := _m.Called(campaign)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*MetaCampaign) error); ok {
		r0 = rf(campaign)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertBatch provides a mock function with given fields: campaigns
func (_m *MockRepository) UpsertBatch(campaigns []MetaCampaign) error {
	ret := _m.Called(campaigns)

	if len(ret) == 0 {
		panic("no return value specified for UpsertBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]MetaCampaign) error); ok {
		r0 = rf(campaigns)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
