// Code generated by mockery v2.53.6. DO NOT EDIT.

package insight

import mock "github.com/stretchr/testify/mock"

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// FindAdInsights provides a mock function with given fields: filter
func (_m *MockRepository) FindAdInsights(filter InsightFilter) ([]MetaInsight, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAdInsights")
	}

	var r0 []MetaInsight
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(InsightFilter) ([]MetaInsight, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(InsightFilter) []MetaInsight); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MetaInsight)
		}
	}

	if rf, ok := ret.Get(1).(func(InsightFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(InsightFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindCampaignInsights provides a mock function with given fields: filter
func (_m *MockRepository) FindCampaignInsights(filter InsightFilter) ([]MetaInsight, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindCampaignInsights")
	}

	var r0 []MetaInsight
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(InsightFilter) ([]MetaInsight, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(InsightFilter) []MetaInsight); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MetaInsight)
		}
	}

	if rf, ok := ret.Get(1).(func(InsightFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(InsightFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpsertBatch provides a mock function with given fields: insights
func (_m *MockRepository) UpsertBatch(insights []MetaInsight) error {
	ret := _m.Called(insights)

	if len(ret) == 0 {
		panic("no return value specified for UpsertBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]MetaInsight) error); ok {
		r0 = rf(insights)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
