// Code generated by mockery v2.53.6. DO NOT EDIT.

package insight

import (
	dto "github.com/alex/ads_backend/internal/meta/insight/dto"
	mock "github.com/stretchr/testify/mock"

	response "github.com/alex/ads_backend/pkg/response"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// GetAdInsights provides a mock function with given fields: filter
func (_m *MockService) GetAdInsights(filter InsightFilter) ([]dto.InsightResponse, *response.PaginationMeta, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAdInsights")
	}

	var r0 []dto.InsightResponse
	var r1 *response.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(InsightFilter) ([]dto.InsightResponse, *response.PaginationMeta, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(InsightFilter) []dto.InsightResponse); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.InsightResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(InsightFilter) *response.PaginationMeta); ok {
		r1 = rf(filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.PaginationMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(InsightFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetCampaignInsights provides a mock function with given fields: filter
func (_m *MockService) GetCampaignInsights(filter InsightFilter) ([]dto.InsightResponse, *response.PaginationMeta, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaignInsights")
	}

	var r0 []dto.InsightResponse
	var r1 *response.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(InsightFilter) ([]dto.InsightResponse, *response.PaginationMeta, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(InsightFilter) []dto.InsightResponse); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.InsightResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(InsightFilter) *response.PaginationMeta); ok {
		r1 = rf(filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.PaginationMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(InsightFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SyncAdInsights provides a mock function with given fields: req
func (_m *MockService) SyncAdInsights(req dto.SyncInsightRequest) (int, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for SyncAdInsights")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.SyncInsightRequest) (int, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(dto.SyncInsightRequest) int); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(dto.SyncInsightRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SyncCampaignInsights provides a mock function with given fields: req
func (_m *MockService) SyncCampaignInsights(req dto.SyncInsightRequest) (int, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for SyncCampaignInsights")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.SyncInsightRequest) (int, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(dto.SyncInsightRequest) int); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(dto.SyncInsightRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
