// Code generated by mockery v2.53.6. DO NOT EDIT.

package business

import mock "github.com/stretchr/testify/mock"

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: filter
func (_m *MockRepository) FindAll(filter BusinessFilter) ([]MetaBusiness, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []MetaBusiness
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(BusinessFilter) ([]MetaBusiness, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(BusinessFilter) []MetaBusiness); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MetaBusiness)
		}
	}

	if rf, ok := ret.Get(1).(func(BusinessFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(BusinessFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: id
func (_m *MockRepository) FindByID(id string) (*MetaBusiness, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *MetaBusiness
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*MetaBusiness, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *MetaBusiness); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MetaBusiness)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUniqueBusinessIDsFromAdAccounts provides a mock function with no fields
func (_m *MockRepository) GetUniqueBusinessIDsFromAdAccounts() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUniqueBusinessIDsFromAdAccounts")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertBatch provides a mock function with given fields: businesses
func (_m *MockRepository) UpsertBatch(businesses []MetaBusiness) error {
	ret := _m.Called(businesses)

	if len(ret) == 0 {
		panic("no return value specified for UpsertBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]MetaBusiness) error); ok {
		r0 = rf(businesses)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
