// Code generated by mockery v2.53.6. DO NOT EDIT.

package business

import (
	dto "github.com/alex/ads_backend/internal/meta/business/dto"
	mock "github.com/stretchr/testify/mock"

	response "github.com/alex/ads_backend/pkg/response"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// GetBusinesses provides a mock function with given fields: filter
func (_m *MockService) GetBusinesses(filter BusinessFilter) ([]dto.BusinessResponse, *response.Meta, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetBusinesses")
	}

	var r0 []dto.BusinessResponse
	var r1 *response.Meta
	var r2 error
	if rf, ok := ret.Get(0).(func(BusinessFilter) ([]dto.BusinessResponse, *response.Meta, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(BusinessFilter) []dto.BusinessResponse); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.BusinessResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(BusinessFilter) *response.Meta); ok {
		r1 = rf(filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.Meta)
		}
	}

	if rf, ok := ret.Get(2).(func(BusinessFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SyncBusinesses provides a mock function with no fields
func (_m *MockService) SyncBusinesses() (int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SyncBusinesses")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
