// Code generated by mockery v2.53.6. DO NOT EDIT.

package activity

import (
	dto "github.com/alex/ads_backend/internal/meta/activity/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// FindAllByBrand provides a mock function with given fields: brandID, filter
func (_m *MockRepository) FindAllByBrand(brandID uint64, filter dto.ActivityFilter) ([]ActivityWithAdAccount, int64, error) {
	ret := _m.Called(brandID, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByBrand")
	}

	var r0 []ActivityWithAdAccount
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uint64, dto.ActivityFilter) ([]ActivityWithAdAccount, int64, error)); ok {
		return rf(brandID, filter)
	}
	if rf, ok := ret.Get(0).(func(uint64, dto.ActivityFilter) []ActivityWithAdAccount); ok {
		r0 = rf(brandID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ActivityWithAdAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, dto.ActivityFilter) int64); ok {
		r1 = rf(brandID, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uint64, dto.ActivityFilter) error); ok {
		r2 = rf(brandID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpsertBatch provides a mock function with given fields: activities
func (_m *MockRepository) UpsertBatch(activities []MetaActivity) error {
	ret := _m.Called(activities)

	if len(ret) == 0 {
		panic("no return value specified for UpsertBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]MetaActivity) error); ok {
		r0 = rf(activities)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
