// Code generated by mockery v2.53.6. DO NOT EDIT.

package activity

import (
	dto "github.com/alex/ads_backend/internal/meta/activity/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// FindAllByBrand provides a mock function with given fields: brandID, filter
func (_m *MockService) FindAllByBrand(brandID uint64, filter dto.ActivityFilter) ([]dto.ActivityResponse, int64, error) {
	ret := _m.Called(brandID, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByBrand")
	}

	var r0 []dto.ActivityResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uint64, dto.ActivityFilter) ([]dto.ActivityResponse, int64, error)); ok {
		return rf(brandID, filter)
	}
	if rf, ok := ret.Get(0).(func(uint64, dto.ActivityFilter) []dto.ActivityResponse); ok {
		r0 = rf(brandID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ActivityResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, dto.ActivityFilter) int64); ok {
		r1 = rf(brandID, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uint64, dto.ActivityFilter) error); ok {
		r2 = rf(brandID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SyncActivities provides a mock function with given fields: adAccountID
func (_m *MockService) SyncActivities(adAccountID string) (int, error) {
	ret := _m.Called(adAccountID)

	if len(ret) == 0 {
		panic("no return value specified for SyncActivities")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(adAccountID)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(adAccountID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(adAccountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
