// Code generated by mockery v2.53.6. DO NOT EDIT.

package adset

import (
	dto "github.com/alex/ads_backend/internal/meta/adset/dto"
	mock "github.com/stretchr/testify/mock"

	response "github.com/alex/ads_backend/pkg/response"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// GetAdSets provides a mock function with given fields: filter
func (_m *MockService) GetAdSets(filter AdSetFilter) ([]dto.AdSetResponse, *response.PaginationMeta, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAdSets")
	}

	var r0 []dto.AdSetResponse
	var r1 *response.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(AdSetFilter) ([]dto.AdSetResponse, *response.PaginationMeta, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(AdSetFilter) []dto.AdSetResponse); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.AdSetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(AdSetFilter) *response.PaginationMeta); ok {
		r1 = rf(filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.PaginationMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(AdSetFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SyncAdSets provides a mock function with given fields: adAccountID
func (_m *MockService) SyncAdSets(adAccountID string) (int, error) {
	ret := _m.Called(adAccountID)

	if len(ret) == 0 {
		panic("no return value specified for SyncAdSets")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(adAccountID)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(adAccountID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(adAccountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
