// Code generated by mockery v2.53.6. DO NOT EDIT.

package adset

import (
	dto "github.com/alex/ads_backend/internal/meta/adset/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// FindAdSetDashboard provides a mock function with given fields: filter
func (_m *MockRepository) FindAdSetDashboard(filter AdSetFilter) ([]adSetDashboardScan, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAdSetDashboard")
	}

	var r0 []adSetDashboardScan
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(AdSetFilter) ([]adSetDashboardScan, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(AdSetFilter) []adSetDashboardScan); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]adSetDashboardScan)
		}
	}

	if rf, ok := ret.Get(1).(func(AdSetFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(AdSetFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindAll provides a mock function with given fields: filter
func (_m *MockRepository) FindAll(filter AdSetFilter) ([]MetaAdSet, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []MetaAdSet
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(AdSetFilter) ([]MetaAdSet, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(AdSetFilter) []MetaAdSet); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MetaAdSet)
		}
	}

	if rf, ok := ret.Get(1).(func(AdSetFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(AdSetFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByCampaignID provides a mock function with given fields: campaignID
func (_m *MockRepository) FindByCampaignID(campaignID string) ([]MetaAdSet, error) {
	ret := _m.Called(campaignID)

	if len(ret) == 0 {
		panic("no return value specified for FindByCampaignID")
	}

	var r0 []MetaAdSet
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]MetaAdSet, error)); ok {
		return rf(campaignID)
	}
	if rf, ok := ret.Get(0).(func(string) []MetaAdSet); ok {
		r0 = rf(campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MetaAdSet)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindSimpleListByBrand provides a mock function with given fields: brandID, campaignIDs
func (_m *MockRepository) FindSimpleListByBrand(brandID uint64, campaignIDs []string) ([]dto.SimpleListResponse, error) {
	ret := _m.Called(brandID, campaignIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindSimpleListByBrand")
	}

	var r0 []dto.SimpleListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, []string) ([]dto.SimpleListResponse, error)); ok {
		return rf(brandID, campaignIDs)
	}
	if rf, ok := ret.Get(0).(func(uint64, []string) []dto.SimpleListResponse); ok {
		r0 = rf(brandID, campaignIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.SimpleListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, []string) error); ok {
		r1 = rf(brandID, campaignIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: adset
func (_m *MockRepository) Upsert(adset *MetaAdSet) error {
	ret := _m.Called(adset)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*MetaAdSet) error); ok {
		r0 = rf(adset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertBatch provides a mock function with given fields: adsets
func (_m *MockRepository) UpsertBatch(adsets []MetaAdSet) error {
	ret := _m.Called(adsets)

	if len(ret) == 0 {
		panic("no return value specified for UpsertBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]MetaAdSet) error); ok {
		r0 = rf(adsets)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
