// Code generated by mockery v2.53.6. DO NOT EDIT.

package permission

import (
	dto "github.com/alex/ads_backend/internal/core/permission/dto"
	mock "github.com/stretchr/testify/mock"

	response "github.com/alex/ads_backend/pkg/response"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// Create provides a mock function with given fields: req
func (_m *MockService) Create(req dto.PermissionRequest) (*Permission, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.PermissionRequest) (*Permission, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(dto.PermissionRequest) *Permission); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.PermissionRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *MockService) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: filter
func (_m *MockService) FindAll(filter dto.PermissionFilter) ([]dto.PermissionResponse, *response.PaginationMeta, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []dto.PermissionResponse
	var r1 *response.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(dto.PermissionFilter) ([]dto.PermissionResponse, *response.PaginationMeta, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(dto.PermissionFilter) []dto.PermissionResponse); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.PermissionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.PermissionFilter) *response.PaginationMeta); ok {
		r1 = rf(filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.PaginationMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(dto.PermissionFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: id
func (_m *MockService) FindByID(id uint) (*dto.PermissionResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *dto.PermissionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*dto.PermissionResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *dto.PermissionResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PermissionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, req
func (_m *MockService) Update(id uint, req dto.PermissionRequest) (*Permission, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, dto.PermissionRequest) (*Permission, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(uint, dto.PermissionRequest) *Permission); ok {
		r0 = rf(id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, dto.PermissionRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
