// Code generated by mockery v2.53.6. DO NOT EDIT.

package permission

import (
	dto "github.com/alex/ads_backend/internal/core/permission/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: permission
func (_m *MockRepository) Create(permission *Permission) error {
	ret := _m.Called(permission)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*Permission) error); ok {
		r0 = rf(permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *MockRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with no fields
func (_m *MockRepository) FindAll() ([]Permission, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []Permission
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]Permission, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []Permission); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Permission)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *MockRepository) FindByID(id uint) (*Permission, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*Permission, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *Permission); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIDs provides a mock function with given fields: ids
func (_m *MockRepository) FindByIDs(ids []uint) ([]Permission, error) {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []Permission
	var r1 error
	if rf, ok := ret.Get(0).(func([]uint) ([]Permission, error)); ok {
		return rf(ids)
	}
	if rf, ok := ret.Get(0).(func([]uint) []Permission); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Permission)
		}
	}

	if rf, ok := ret.Get(1).(func([]uint) error); ok {
		r1 = rf(ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPaginated provides a mock function with given fields: filter
func (_m *MockRepository) FindPaginated(filter dto.PermissionFilter) ([]Permission, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindPaginated")
	}

	var r0 []Permission
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(dto.PermissionFilter) ([]Permission, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(dto.PermissionFilter) []Permission); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.PermissionFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(dto.PermissionFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: permission
func (_m *MockRepository) Update(permission *Permission) error {
	ret := _m.Called(permission)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*Permission) error); ok {
		r0 = rf(permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
