ALTER TABLE meta_insights 
MODIFY inline_link_click_ctr DECIMAL(20,4) DEFAULT 0,
MODIFY spend DECIMAL(20,4) DEFAULT 0,
MODIFY cpc DECIMAL(20,4) DEFAULT 0,
MODIFY cpm DECIMAL(20,4) DEFAULT 0,
MODIFY ctr DECIMAL(20,4) DEFAULT 0;
