ALTER TABLE meta_insights 
MODIFY inline_link_click_ctr DECIMAL(10,4) DEFAULT 0,
MODIFY spend DECIMAL(15,2) DEFAULT 0,
MODIFY cpc DECIMAL(10,4) DEFAULT 0,
MODIFY cpm DECIMAL(10,4) DEFAULT 0,
MODIFY ctr DECIMAL(10,4) DEFAULT 0;
