CREATE TABLE IF NOT EXISTS meta_campaigns (
    id               VARCHAR(50) PRIMARY KEY,
    account_id       VARCHAR(50) NOT NULL,
    name             VARCHAR(500) NOT NULL,
    status           VARCHAR(50) NOT NULL,
    effective_status VARCHAR(50),
    objective        VARCHAR(100),
    buying_type      VARCHAR(50),
    daily_budget     DECIMAL(15,2) DEFAULT 0,
    lifetime_budget  DECIMAL(15,2) DEFAULT 0,
    budget_remaining DECIMAL(15,2) DEFAULT 0,
    spend_cap        DECIMAL(15,2) DEFAULT 0,
    bid_strategy     VARCHAR(100),
    start_time       TIMESTAMP NULL,
    stop_time        TIMESTAMP NULL,
    created_time     TIMESTAMP NULL,
    updated_time     TIMESTAMP NULL,
    synced_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_meta_campaigns_account_id (account_id),
    INDEX idx_meta_campaigns_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meta_ad_sets (
    id               VARCHAR(50) PRIMARY KEY,
    campaign_id      VARCHAR(50) NOT NULL,
    name             VARCHAR(500) NOT NULL,
    status           VARCHAR(50) NOT NULL,
    effective_status VARCHAR(50),
    daily_budget     DECIMAL(15,2) DEFAULT 0,
    lifetime_budget  DECIMAL(15,2) DEFAULT 0,
    budget_remaining DECIMAL(15,2) DEFAULT 0,
    bid_strategy     VARCHAR(100),
    attribution_spec JSON,
    start_time       TIMESTAMP NULL,
    end_time         TIMESTAMP NULL,
    created_time     TIMESTAMP NULL,
    updated_time     TIMESTAMP NULL,
    synced_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_meta_ad_sets_campaign_id (campaign_id),
    INDEX idx_meta_ad_sets_status (status),
    FOREIGN KEY (campaign_id) REFERENCES meta_campaigns(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meta_ads (
    id               VARCHAR(50) PRIMARY KEY,
    campaign_id      VARCHAR(50) NOT NULL,
    adset_id         VARCHAR(50) NOT NULL,
    name             VARCHAR(500) NOT NULL,
    status           VARCHAR(50) NOT NULL,
    effective_status VARCHAR(50),
    creative_id      VARCHAR(50),
    created_time     TIMESTAMP NULL,
    updated_time     TIMESTAMP NULL,
    synced_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_meta_ads_campaign_id (campaign_id),
    INDEX idx_meta_ads_adset_id (adset_id),
    INDEX idx_meta_ads_status (status),
    FOREIGN KEY (campaign_id) REFERENCES meta_campaigns(id) ON DELETE CASCADE,
    FOREIGN KEY (adset_id) REFERENCES meta_ad_sets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meta_insights (
    id                    BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    account_id            VARCHAR(50) NOT NULL,
    account_name          VARCHAR(255),
    account_currency      VARCHAR(10),
    campaign_id           VARCHAR(50) NOT NULL,
    campaign_name         VARCHAR(500),
    adset_id              VARCHAR(50) NOT NULL DEFAULT '',
    adset_name            VARCHAR(500),
    ad_id                 VARCHAR(50) NOT NULL DEFAULT '',
    ad_name               VARCHAR(500),
    level                 VARCHAR(20) NOT NULL,
    objective             VARCHAR(100),
    impressions           BIGINT DEFAULT 0,
    reach                 BIGINT DEFAULT 0,
    clicks                BIGINT DEFAULT 0,
    inline_link_clicks    BIGINT DEFAULT 0,
    inline_link_click_ctr DECIMAL(10,4) DEFAULT 0,
    spend                 DECIMAL(15,2) DEFAULT 0,
    cpc                   DECIMAL(10,4) DEFAULT 0,
    cpm                   DECIMAL(10,4) DEFAULT 0,
    ctr                   DECIMAL(10,4) DEFAULT 0,
    actions               JSON,
    action_values         JSON,
    cost_per_action_type  JSON,
    date_start            DATE NOT NULL,
    date_stop             DATE NOT NULL,
    synced_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_meta_insight (campaign_id, adset_id, ad_id, level, date_start, date_stop),
    INDEX idx_meta_insights_campaign_id (campaign_id),
    INDEX idx_meta_insights_level (level),
    INDEX idx_meta_insights_date_range (date_start, date_stop)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
