// Code generated by mockery v2.53.6. DO NOT EDIT.

package dashboard

import mock "github.com/stretchr/testify/mock"

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// FindAdDashboard provides a mock function with given fields: filter
func (_m *MockRepository) FindAdDashboard(filter DashboardFilter) ([]adDashboardScan, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAdDashboard")
	}

	var r0 []adDashboardScan
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(DashboardFilter) ([]adDashboardScan, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(DashboardFilter) []adDashboardScan); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]adDashboardScan)
		}
	}

	if rf, ok := ret.Get(1).(func(DashboardFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(DashboardFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindAdSetDashboard provides a mock function with given fields: filter
func (_m *MockRepository) FindAdSetDashboard(filter DashboardFilter) ([]adSetDashboardScan, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAdSetDashboard")
	}

	var r0 []adSetDashboardScan
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(DashboardFilter) ([]adSetDashboardScan, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(DashboardFilter) []adSetDashboardScan); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]adSetDashboardScan)
		}
	}

	if rf, ok := ret.Get(1).(func(DashboardFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(DashboardFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindBrandDashboard provides a mock function with given fields: filter
func (_m *MockRepository) FindBrandDashboard(filter DashboardFilter) ([]brandDashboardScan, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindBrandDashboard")
	}

	var r0 []brandDashboardScan
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(DashboardFilter) ([]brandDashboardScan, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(DashboardFilter) []brandDashboardScan); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]brandDashboardScan)
		}
	}

	if rf, ok := ret.Get(1).(func(DashboardFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(DashboardFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindCampaignDashboard provides a mock function with given fields: filter
func (_m *MockRepository) FindCampaignDashboard(filter DashboardFilter) ([]campaignDashboardScan, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindCampaignDashboard")
	}

	var r0 []campaignDashboardScan
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(DashboardFilter) ([]campaignDashboardScan, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(DashboardFilter) []campaignDashboardScan); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]campaignDashboardScan)
		}
	}

	if rf, ok := ret.Get(1).(func(DashboardFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(DashboardFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
