// Code generated by mockery v2.53.6. DO NOT EDIT.

package dashboard

import (
	dto "github.com/alex/ads_backend/internal/meta/dashboard/dto"
	mock "github.com/stretchr/testify/mock"

	response "github.com/alex/ads_backend/pkg/response"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// GetAdDashboard provides a mock function with given fields: filter
func (_m *MockService) GetAdDashboard(filter DashboardFilter) ([]dto.AdDashboardRow, *response.PaginationMeta, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAdDashboard")
	}

	var r0 []dto.AdDashboardRow
	var r1 *response.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(DashboardFilter) ([]dto.AdDashboardRow, *response.PaginationMeta, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(DashboardFilter) []dto.AdDashboardRow); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.AdDashboardRow)
		}
	}

	if rf, ok := ret.Get(1).(func(DashboardFilter) *response.PaginationMeta); ok {
		r1 = rf(filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.PaginationMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(DashboardFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetAdSetDashboard provides a mock function with given fields: filter
func (_m *MockService) GetAdSetDashboard(filter DashboardFilter) ([]dto.AdSetDashboardRow, *response.PaginationMeta, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAdSetDashboard")
	}

	var r0 []dto.AdSetDashboardRow
	var r1 *response.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(DashboardFilter) ([]dto.AdSetDashboardRow, *response.PaginationMeta, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(DashboardFilter) []dto.AdSetDashboardRow); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.AdSetDashboardRow)
		}
	}

	if rf, ok := ret.Get(1).(func(DashboardFilter) *response.PaginationMeta); ok {
		r1 = rf(filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.PaginationMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(DashboardFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetCampaignDashboard provides a mock function with given fields: filter
func (_m *MockService) GetCampaignDashboard(filter DashboardFilter) ([]dto.CampaignDashboardRow, *response.PaginationMeta, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaignDashboard")
	}

	var r0 []dto.CampaignDashboardRow
	var r1 *response.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(DashboardFilter) ([]dto.CampaignDashboardRow, *response.PaginationMeta, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(DashboardFilter) []dto.CampaignDashboardRow); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.CampaignDashboardRow)
		}
	}

	if rf, ok := ret.Get(1).(func(DashboardFilter) *response.PaginationMeta); ok {
		r1 = rf(filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.PaginationMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(DashboardFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
