// Code generated by mockery v2.53.6. DO NOT EDIT.

package ad_account

import (
	dto "github.com/alex/ads_backend/internal/meta/ad_account/dto"
	mock "github.com/stretchr/testify/mock"

	response "github.com/alex/ads_backend/pkg/response"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// BulkAssignBrand provides a mock function with given fields: ids, brandID
func (_m *MockService) BulkAssignBrand(ids []string, brandID *uint64) error {
	ret := _m.Called(ids, brandID)

	if len(ret) == 0 {
		panic("no return value specified for BulkAssignBrand")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, *uint64) error); ok {
		r0 = rf(ids, brandID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DisconnectBrand provides a mock function with given fields: id
func (_m *MockService) DisconnectBrand(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DisconnectBrand")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAdAccounts provides a mock function with given fields: filter
func (_m *MockService) GetAdAccounts(filter AdAccountFilter) ([]dto.AdAccountResponse, *response.Meta, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAdAccounts")
	}

	var r0 []dto.AdAccountResponse
	var r1 *response.Meta
	var r2 error
	if rf, ok := ret.Get(0).(func(AdAccountFilter) ([]dto.AdAccountResponse, *response.Meta, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(AdAccountFilter) []dto.AdAccountResponse); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.AdAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(AdAccountFilter) *response.Meta); ok {
		r1 = rf(filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.Meta)
		}
	}

	if rf, ok := ret.Get(2).(func(AdAccountFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetBusinessOptions provides a mock function with no fields
func (_m *MockService) GetBusinessOptions() ([]dto.BusinessOptionResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBusinessOptions")
	}

	var r0 []dto.BusinessOptionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]dto.BusinessOptionResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []dto.BusinessOptionResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.BusinessOptionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnassigned provides a mock function with given fields: filter
func (_m *MockService) GetUnassigned(filter AdAccountFilter) ([]dto.AdAccountResponse, *response.Meta, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetUnassigned")
	}

	var r0 []dto.AdAccountResponse
	var r1 *response.Meta
	var r2 error
	if rf, ok := ret.Get(0).(func(AdAccountFilter) ([]dto.AdAccountResponse, *response.Meta, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(AdAccountFilter) []dto.AdAccountResponse); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.AdAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(AdAccountFilter) *response.Meta); ok {
		r1 = rf(filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.Meta)
		}
	}

	if rf, ok := ret.Get(2).(func(AdAccountFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SyncAdAccounts provides a mock function with no fields
func (_m *MockService) SyncAdAccounts() (int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SyncAdAccounts")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
