// Code generated by mockery v2.53.6. DO NOT EDIT.

package ad_account

import (
	dto "github.com/alex/ads_backend/internal/meta/ad_account/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: filter
func (_m *MockRepository) FindAll(filter AdAccountFilter) ([]MetaAdAccount, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []MetaAdAccount
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(AdAccountFilter) ([]MetaAdAccount, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(AdAccountFilter) []MetaAdAccount); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MetaAdAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(AdAccountFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(AdAccountFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: id
func (_m *MockRepository) FindByID(id string) (*MetaAdAccount, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *MetaAdAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*MetaAdAccount, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *MetaAdAccount); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MetaAdAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUnassigned provides a mock function with given fields: filter
func (_m *MockRepository) FindUnassigned(filter AdAccountFilter) ([]MetaAdAccount, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindUnassigned")
	}

	var r0 []MetaAdAccount
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(AdAccountFilter) ([]MetaAdAccount, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(AdAccountFilter) []MetaAdAccount); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MetaAdAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(AdAccountFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(AdAccountFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetUniqueBusinesses provides a mock function with no fields
func (_m *MockRepository) GetUniqueBusinesses() ([]dto.BusinessOptionResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUniqueBusinesses")
	}

	var r0 []dto.BusinessOptionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]dto.BusinessOptionResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []dto.BusinessOptionResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.BusinessOptionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: account
func (_m *MockRepository) Update(account *MetaAdAccount) error {
	ret := _m.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*MetaAdAccount) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBrandID provides a mock function with given fields: id, brandID
func (_m *MockRepository) UpdateBrandID(id string, brandID *uint64) error {
	ret := _m.Called(id, brandID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBrandID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *uint64) error); ok {
		r0 = rf(id, brandID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBrandIDBatch provides a mock function with given fields: ids, brandID
func (_m *MockRepository) UpdateBrandIDBatch(ids []string, brandID *uint64) error {
	ret := _m.Called(ids, brandID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBrandIDBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, *uint64) error); ok {
		r0 = rf(ids, brandID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBrandIDByBusiness provides a mock function with given fields: businessID, brandID
func (_m *MockRepository) UpdateBrandIDByBusiness(businessID string, brandID *uint64) error {
	ret := _m.Called(businessID, brandID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBrandIDByBusiness")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *uint64) error); ok {
		r0 = rf(businessID, brandID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertBatch provides a mock function with given fields: accounts
func (_m *MockRepository) UpsertBatch(accounts []MetaAdAccount) error {
	ret := _m.Called(accounts)

	if len(ret) == 0 {
		panic("no return value specified for UpsertBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]MetaAdAccount) error); ok {
		r0 = rf(accounts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
