// Code generated by mockery v2.53.6. DO NOT EDIT.

package ad_creative

import mock "github.com/stretchr/testify/mock"

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// SyncCreatives provides a mock function with given fields: adAccountID, adsList
func (_m *MockService) SyncCreatives(adAccountID string, adsList []AdRecord) (int, error) {
	ret := _m.Called(adAccountID, adsList)

	if len(ret) == 0 {
		panic("no return value specified for SyncCreatives")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []AdRecord) (int, error)); ok {
		return rf(adAccountID, adsList)
	}
	if rf, ok := ret.Get(0).(func(string, []AdRecord) int); ok {
		r0 = rf(adAccountID, adsList)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string, []AdRecord) error); ok {
		r1 = rf(adAccountID, adsList)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
