// Code generated by mockery v2.53.6. DO NOT EDIT.

package ad_creative

import mock "github.com/stretchr/testify/mock"

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// CreateVersion provides a mock function with given fields: version
func (_m *MockRepository) CreateVersion(version *AdCreativeVersion) error {
	ret := _m.Called(version)

	if len(ret) == 0 {
		panic("no return value specified for CreateVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*AdCreativeVersion) error); ok {
		r0 = rf(version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByCreativeID provides a mock function with given fields: creativeID
func (_m *MockRepository) FindByCreativeID(creativeID string) (*AdCreative, error) {
	ret := _m.Called(creativeID)

	if len(ret) == 0 {
		panic("no return value specified for FindByCreativeID")
	}

	var r0 *AdCreative
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*AdCreative, error)); ok {
		return rf(creativeID)
	}
	if rf, ok := ret.Get(0).(func(string) *AdCreative); ok {
		r0 = rf(creativeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AdCreative)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(creativeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindLatestVersionByCreativeID provides a mock function with given fields: creativeID
func (_m *MockRepository) FindLatestVersionByCreativeID(creativeID string) (*AdCreativeVersion, error) {
	ret := _m.Called(creativeID)

	if len(ret) == 0 {
		panic("no return value specified for FindLatestVersionByCreativeID")
	}

	var r0 *AdCreativeVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*AdCreativeVersion, error)); ok {
		return rf(creativeID)
	}
	if rf, ok := ret.Get(0).(func(string) *AdCreativeVersion); ok {
		r0 = rf(creativeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AdCreativeVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(creativeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: creative
func (_m *MockRepository) Upsert(creative *AdCreative) error {
	ret := _m.Called(creative)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*AdCreative) error); ok {
		r0 = rf(creative)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
