// Code generated by mockery v2.53.6. DO NOT EDIT.

package brand_whitelist_rule

import (
	dto "github.com/alex/ads_backend/internal/core/brand_whitelist_rule/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// Create provides a mock function with given fields: brandID, req
func (_m *MockService) Create(brandID uint64, req dto.CreateWhitelistRuleRequest) (dto.WhitelistRuleResponse, error) {
	ret := _m.Called(brandID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 dto.WhitelistRuleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, dto.CreateWhitelistRuleRequest) (dto.WhitelistRuleResponse, error)); ok {
		return rf(brandID, req)
	}
	if rf, ok := ret.Get(0).(func(uint64, dto.CreateWhitelistRuleRequest) dto.WhitelistRuleResponse); ok {
		r0 = rf(brandID, req)
	} else {
		r0 = ret.Get(0).(dto.WhitelistRuleResponse)
	}

	if rf, ok := ret.Get(1).(func(uint64, dto.CreateWhitelistRuleRequest) error); ok {
		r1 = rf(brandID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: brandID, id
func (_m *MockService) Delete(brandID uint64, id uint64) error {
	ret := _m.Called(brandID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, uint64) error); ok {
		r0 = rf(brandID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: brandID, filter
func (_m *MockService) FindAll(brandID uint64, filter dto.WhitelistRuleFilter) ([]dto.WhitelistRuleResponse, int64, error) {
	ret := _m.Called(brandID, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []dto.WhitelistRuleResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uint64, dto.WhitelistRuleFilter) ([]dto.WhitelistRuleResponse, int64, error)); ok {
		return rf(brandID, filter)
	}
	if rf, ok := ret.Get(0).(func(uint64, dto.WhitelistRuleFilter) []dto.WhitelistRuleResponse); ok {
		r0 = rf(brandID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.WhitelistRuleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, dto.WhitelistRuleFilter) int64); ok {
		r1 = rf(brandID, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uint64, dto.WhitelistRuleFilter) error); ok {
		r2 = rf(brandID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: brandID, id
func (_m *MockService) FindByID(brandID uint64, id uint64) (dto.WhitelistRuleResponse, error) {
	ret := _m.Called(brandID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 dto.WhitelistRuleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, uint64) (dto.WhitelistRuleResponse, error)); ok {
		return rf(brandID, id)
	}
	if rf, ok := ret.Get(0).(func(uint64, uint64) dto.WhitelistRuleResponse); ok {
		r0 = rf(brandID, id)
	} else {
		r0 = ret.Get(0).(dto.WhitelistRuleResponse)
	}

	if rf, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = rf(brandID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsURLAllowed provides a mock function with given fields: brandID, targetURL, scope
func (_m *MockService) IsURLAllowed(brandID uint64, targetURL string, scope string) (MatchResult, error) {
	ret := _m.Called(brandID, targetURL, scope)

	if len(ret) == 0 {
		panic("no return value specified for IsURLAllowed")
	}

	var r0 MatchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, string, string) (MatchResult, error)); ok {
		return rf(brandID, targetURL, scope)
	}
	if rf, ok := ret.Get(0).(func(uint64, string, string) MatchResult); ok {
		r0 = rf(brandID, targetURL, scope)
	} else {
		r0 = ret.Get(0).(MatchResult)
	}

	if rf, ok := ret.Get(1).(func(uint64, string, string) error); ok {
		r1 = rf(brandID, targetURL, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: brandID, id, req
func (_m *MockService) Update(brandID uint64, id uint64, req dto.UpdateWhitelistRuleRequest) (dto.WhitelistRuleResponse, error) {
	ret := _m.Called(brandID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dto.WhitelistRuleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, uint64, dto.UpdateWhitelistRuleRequest) (dto.WhitelistRuleResponse, error)); ok {
		return rf(brandID, id, req)
	}
	if rf, ok := ret.Get(0).(func(uint64, uint64, dto.UpdateWhitelistRuleRequest) dto.WhitelistRuleResponse); ok {
		r0 = rf(brandID, id, req)
	} else {
		r0 = ret.Get(0).(dto.WhitelistRuleResponse)
	}

	if rf, ok := ret.Get(1).(func(uint64, uint64, dto.UpdateWhitelistRuleRequest) error); ok {
		r1 = rf(brandID, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
