// Code generated by mockery v2.53.6. DO NOT EDIT.

package brand_whitelist_rule

import (
	dto "github.com/alex/ads_backend/internal/core/brand_whitelist_rule/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: rule
func (_m *MockRepository) Create(rule *BrandWhitelistRule) error {
	ret := _m.Called(rule)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*BrandWhitelistRule) error); ok {
		r0 = rf(rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *MockRepository) Delete(id uint64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindActiveByBrandIDAndScope provides a mock function with given fields: brandID, scope
func (_m *MockRepository) FindActiveByBrandIDAndScope(brandID uint64, scope string) ([]BrandWhitelistRule, error) {
	ret := _m.Called(brandID, scope)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByBrandIDAndScope")
	}

	var r0 []BrandWhitelistRule
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, string) ([]BrandWhitelistRule, error)); ok {
		return rf(brandID, scope)
	}
	if rf, ok := ret.Get(0).(func(uint64, string) []BrandWhitelistRule); ok {
		r0 = rf(brandID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BrandWhitelistRule)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, string) error); ok {
		r1 = rf(brandID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByBrandID provides a mock function with given fields: brandID, filter
func (_m *MockRepository) FindAllByBrandID(brandID uint64, filter dto.WhitelistRuleFilter) ([]BrandWhitelistRule, int64, error) {
	ret := _m.Called(brandID, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByBrandID")
	}

	var r0 []BrandWhitelistRule
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uint64, dto.WhitelistRuleFilter) ([]BrandWhitelistRule, int64, error)); ok {
		return rf(brandID, filter)
	}
	if rf, ok := ret.Get(0).(func(uint64, dto.WhitelistRuleFilter) []BrandWhitelistRule); ok {
		r0 = rf(brandID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BrandWhitelistRule)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, dto.WhitelistRuleFilter) int64); ok {
		r1 = rf(brandID, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uint64, dto.WhitelistRuleFilter) error); ok {
		r2 = rf(brandID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: id
func (_m *MockRepository) FindByID(id uint64) (*BrandWhitelistRule, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *BrandWhitelistRule
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*BrandWhitelistRule, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint64) *BrandWhitelistRule); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*BrandWhitelistRule)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: rule
func (_m *MockRepository) Update(rule *BrandWhitelistRule) error {
	ret := _m.Called(rule)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*BrandWhitelistRule) error); ok {
		r0 = rf(rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
