// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate user and return token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Logout user (Clear session/token)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/meta/ad-accounts": {
            "get": {
                "description": "Retrieve all ad accounts associated with the system user token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meta Ad Accounts"
                ],
                "summary": "Get Meta Ad Accounts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Custom fields comma-separated preset",
                        "name": "fields",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cursor after",
                        "name": "after",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cursor before",
                        "name": "before",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.AdAccountResponse"
                                            }
                                        },
                                        "paging": {
                                            "$ref": "#/definitions/response.MetaPaging"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meta/ads": {
            "get": {
                "description": "Retrieve ads from local database (synced from Meta)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meta Ads"
                ],
                "summary": "Get Ads",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by campaign ID",
                        "name": "campaign_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by adset ID",
                        "name": "adset_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status (ACTIVE, PAUSED, etc)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by ad name",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.AdResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/response.PaginationMeta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meta/adsets": {
            "get": {
                "description": "Retrieve adsets from local database (synced from Meta)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meta AdSets"
                ],
                "summary": "Get AdSets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by campaign ID",
                        "name": "campaign_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status (ACTIVE, PAUSED, etc)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by adset name",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.AdSetResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/response.PaginationMeta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meta/campaigns": {
            "get": {
                "description": "Retrieve campaigns from local database (synced from Meta)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meta Campaigns"
                ],
                "summary": "Get Campaigns",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ad Account ID (falls back to config.MetaAdAccountID)",
                        "name": "ad_account_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status (ACTIVE, PAUSED, etc)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by campaign name",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.CampaignResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/response.PaginationMeta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meta/creatives/{id}": {
            "get": {
                "description": "Retrieve details of a specific ad creative (direct Meta API call)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meta Ads"
                ],
                "summary": "Get Ad Creative",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Creative ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Custom fields comma-separated preset",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.CreativeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meta/dashboard/campaigns": {
            "get": {
                "description": "Returns campaigns with performance metrics (spend, impressions, reach, actions) joined from insights and adsets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meta Dashboard"
                ],
                "summary": "Campaign Dashboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ad Account ID (falls back to config)",
                        "name": "ad_account_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by campaign status (ACTIVE, PAUSED, etc)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by campaign name",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meta/insights/ad": {
            "get": {
                "description": "Retrieve ad-level insights from local database (synced from Meta)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meta Insights"
                ],
                "summary": "Get Ad Insights",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by account ID",
                        "name": "account_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by campaign ID",
                        "name": "campaign_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by adset ID",
                        "name": "adset_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by ad ID",
                        "name": "ad_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by date start (YYYY-MM-DD)",
                        "name": "date_start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by date stop (YYYY-MM-DD)",
                        "name": "date_stop",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.InsightResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/response.PaginationMeta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meta/insights/campaign": {
            "get": {
                "description": "Retrieve campaign-level insights from local database (synced from Meta)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meta Insights"
                ],
                "summary": "Get Campaign Insights",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by account ID",
                        "name": "account_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by campaign ID",
                        "name": "campaign_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by date start (YYYY-MM-DD)",
                        "name": "date_start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by date stop (YYYY-MM-DD)",
                        "name": "date_stop",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.InsightResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/response.PaginationMeta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meta/sync": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manually trigger a full Meta Ads sync. Returns immediately; subscribe to the Centrifugo channel for real-time progress.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meta Sync"
                ],
                "summary": "Trigger Meta Ads Sync",
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "409": {
                        "description": "Sync already in progress",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meta/sync/batches": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of sync batches ordered by most recent first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meta Sync"
                ],
                "summary": "List Sync Batches",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.PaginationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/sync.MetaSyncBatch"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meta/sync/batches/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single sync batch with its steps.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meta Sync"
                ],
                "summary": "Get Sync Batch",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Batch ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/sync.MetaSyncBatch"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meta/sync/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns whether a sync job is currently running.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meta Sync"
                ],
                "summary": "Get Sync Status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/permissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all permissions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permission Management"
                ],
                "summary": "Get All Permissions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.PaginationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.PermissionResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new permission",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permission Management"
                ],
                "summary": "Create Permission",
                "parameters": [
                    {
                        "description": "Create Permission Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PermissionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/permissions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a permission by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permission Management"
                ],
                "summary": "Get Permission by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Permission ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.PermissionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update a permission by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permission Management"
                ],
                "summary": "Update Permission",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Permission ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Permission Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PermissionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a permission by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permission Management"
                ],
                "summary": "Delete Permission",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Permission ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/roles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all roles with permissions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role Management"
                ],
                "summary": "Get All Roles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.PaginationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.RoleResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role Management"
                ],
                "summary": "Create Role",
                "parameters": [
                    {
                        "description": "Create Role Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RoleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/roles/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a role by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role Management"
                ],
                "summary": "Get Role by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Role ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.RoleResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update a role by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role Management"
                ],
                "summary": "Update Role",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Role ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Role Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a role by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role Management"
                ],
                "summary": "Delete Role",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Role ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/roles/{id}/permissions": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Assign permissions to a role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role Management"
                ],
                "summary": "Assign Permissions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Role ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Assign Permission Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AssignPermissionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "Get All Users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by email",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.PaginationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.UserResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "Register User",
                "parameters": [
                    {
                        "description": "Create User Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a user by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "Get User by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update a user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "Update User",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update User Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "Delete User",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AdAccountResponse": {
            "type": "object",
            "properties": {
                "account_status": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "string",
                    "example": "act_123456789"
                },
                "name": {
                    "type": "string",
                    "example": "My Ad Account"
                }
            }
        },
        "dto.AdResponse": {
            "type": "object",
            "properties": {
                "adset_id": {
                    "type": "string",
                    "example": "2389876543210"
                },
                "campaign_id": {
                    "type": "string",
                    "example": "2381234567890"
                },
                "created_time": {
                    "type": "string",
                    "example": "2026-05-11T10:00:00Z"
                },
                "creative": {
                    "$ref": "#/definitions/dto.CreativeRef"
                },
                "effective_status": {
                    "type": "string",
                    "example": "ACTIVE"
                },
                "id": {
                    "type": "string",
                    "example": "2386543210987"
                },
                "name": {
                    "type": "string",
                    "example": "Promo Image Ad"
                },
                "status": {
                    "type": "string",
                    "example": "ACTIVE"
                },
                "updated_time": {
                    "type": "string",
                    "example": "2026-05-11T12:00:00Z"
                }
            }
        },
        "dto.AdSetResponse": {
            "type": "object",
            "properties": {
                "attribution_spec": {},
                "bid_strategy": {
                    "type": "string",
                    "example": "LOWEST_COST_WITHOUT_CAP"
                },
                "budget_remaining": {
                    "type": "string",
                    "example": "50000"
                },
                "campaign_id": {
                    "type": "string",
                    "example": "2381234567890"
                },
                "created_time": {
                    "type": "string",
                    "example": "2026-05-11T10:00:00Z"
                },
                "daily_budget": {
                    "type": "string",
                    "example": "50000"
                },
                "effective_status": {
                    "type": "string",
                    "example": "ACTIVE"
                },
                "end_time": {
                    "type": "string",
                    "example": "2026-06-11T10:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "2389876543210"
                },
                "lifetime_budget": {
                    "type": "string",
                    "example": "0"
                },
                "name": {
                    "type": "string",
                    "example": "AdSet Leads USA"
                },
                "start_time": {
                    "type": "string",
                    "example": "2026-05-11T10:00:00Z"
                },
                "status": {
                    "type": "string",
                    "example": "ACTIVE"
                },
                "updated_time": {
                    "type": "string",
                    "example": "2026-05-11T12:00:00Z"
                }
            }
        },
        "dto.AssignPermissionRequest": {
            "type": "object",
            "required": [
                "permission_ids"
            ],
            "properties": {
                "permission_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dto.AuthUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.CampaignResponse": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string",
                    "example": "541050504790549"
                },
                "bid_strategy": {
                    "type": "string",
                    "example": "LOWEST_COST_WITHOUT_CAP"
                },
                "budget_remaining": {
                    "type": "string",
                    "example": "50000"
                },
                "buying_type": {
                    "type": "string",
                    "example": "AUCTION"
                },
                "created_time": {
                    "type": "string",
                    "example": "2026-05-11T10:00:00Z"
                },
                "daily_budget": {
                    "type": "string",
                    "example": "50000"
                },
                "effective_status": {
                    "type": "string",
                    "example": "ACTIVE"
                },
                "id": {
                    "type": "string",
                    "example": "2381234567890"
                },
                "lifetime_budget": {
                    "type": "string",
                    "example": "0"
                },
                "name": {
                    "type": "string",
                    "example": "Summer Sale Campaign"
                },
                "objective": {
                    "type": "string",
                    "example": "OUTCOMES_LEADS"
                },
                "spend_cap": {
                    "type": "string",
                    "example": "0"
                },
                "start_time": {
                    "type": "string",
                    "example": "2026-05-11T10:00:00Z"
                },
                "status": {
                    "type": "string",
                    "example": "ACTIVE"
                },
                "stop_time": {
                    "type": "string",
                    "example": "2026-06-11T10:00:00Z"
                },
                "updated_time": {
                    "type": "string",
                    "example": "2026-05-11T12:00:00Z"
                }
            }
        },
        "dto.CreativeRef": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "2387654321098"
                }
            }
        },
        "dto.CreativeResponse": {
            "type": "object",
            "properties": {
                "asset_feed_spec": {},
                "body": {
                    "type": "string",
                    "example": "Get 20% off today!"
                },
                "id": {
                    "type": "string",
                    "example": "2387654321098"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://scontent.xx.fbcdn.net/..."
                },
                "name": {
                    "type": "string",
                    "example": "Creative Promo 1"
                },
                "object_story_spec": {},
                "thumbnail_url": {
                    "type": "string",
                    "example": "https://scontent.xx.fbcdn.net/..."
                },
                "title": {
                    "type": "string",
                    "example": "Special Offer"
                },
                "url_tags": {
                    "type": "string",
                    "example": "utm_source=facebook\u0026utm_medium=cpc"
                }
            }
        },
        "dto.InsightResponse": {
            "type": "object",
            "properties": {
                "account_currency": {
                    "type": "string",
                    "example": "USD"
                },
                "account_id": {
                    "type": "string",
                    "example": "541050504790549"
                },
                "account_name": {
                    "type": "string",
                    "example": "My Ad Account"
                },
                "action_values": {},
                "actions": {},
                "ad_id": {
                    "type": "string",
                    "example": "2386543210987"
                },
                "ad_name": {
                    "type": "string",
                    "example": "Promo Image Ad"
                },
                "adset_id": {
                    "type": "string",
                    "example": "2389876543210"
                },
                "adset_name": {
                    "type": "string",
                    "example": "AdSet Leads USA"
                },
                "campaign_id": {
                    "type": "string",
                    "example": "2381234567890"
                },
                "campaign_name": {
                    "type": "string",
                    "example": "Summer Sale Campaign"
                },
                "clicks": {
                    "type": "string",
                    "example": "350"
                },
                "cost_per_action_type": {},
                "cpc": {
                    "type": "string",
                    "example": "0.36"
                },
                "cpm": {
                    "type": "string",
                    "example": "8.26"
                },
                "ctr": {
                    "type": "string",
                    "example": "2.30"
                },
                "date_start": {
                    "type": "string",
                    "example": "2026-04-11"
                },
                "date_stop": {
                    "type": "string",
                    "example": "2026-05-11"
                },
                "impressions": {
                    "type": "string",
                    "example": "15200"
                },
                "inline_link_click_ctr": {
                    "type": "string",
                    "example": "2.0"
                },
                "inline_link_clicks": {
                    "type": "string",
                    "example": "300"
                },
                "objective": {
                    "type": "string",
                    "example": "OUTCOMES_LEADS"
                },
                "reach": {
                    "type": "string",
                    "example": "12000"
                },
                "spend": {
                    "type": "string",
                    "example": "125.50"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "centrifugo_token": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.AuthUserResponse"
                }
            }
        },
        "dto.PermissionRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.PermissionResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.RoleBrief": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.RoleRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.RoleResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PermissionResponse"
                    }
                }
            }
        },
        "dto.UserRequest": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "role_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dto.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.RoleBrief"
                    }
                }
            }
        },
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {},
                "message": {
                    "type": "string",
                    "example": "Error message"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "response.Meta": {
            "type": "object",
            "properties": {
                "last_page": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.MetaPaging": {
            "type": "object",
            "properties": {
                "cursors": {
                    "type": "object",
                    "properties": {
                        "after": {
                            "type": "string"
                        },
                        "before": {
                            "type": "string"
                        }
                    }
                },
                "has_next": {
                    "type": "boolean"
                },
                "has_previous": {
                    "type": "boolean"
                }
            }
        },
        "response.PaginationMeta": {
            "type": "object",
            "properties": {
                "last_page": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.PaginationResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Success"
                },
                "meta": {
                    "$ref": "#/definitions/response.Meta"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {},
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/response.Meta"
                },
                "paging": {
                    "$ref": "#/definitions/response.MetaPaging"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Success"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "sync.MetaSyncBatch": {
            "type": "object",
            "properties": {
                "ad_account_id": {
                    "type": "string"
                },
                "ad_account_name": {
                    "type": "string"
                },
                "batch_code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "date_preset": {
                    "type": "string"
                },
                "date_start": {
                    "type": "string"
                },
                "date_stop": {
                    "type": "string"
                },
                "duration_ms": {
                    "type": "integer"
                },
                "error_message": {
                    "type": "string"
                },
                "failed_count": {
                    "type": "integer"
                },
                "finished_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "inserted_count": {
                    "type": "integer"
                },
                "metadata": {
                    "type": "object"
                },
                "provider": {
                    "type": "string"
                },
                "rate_limit_hit": {
                    "type": "boolean"
                },
                "request_count": {
                    "type": "integer"
                },
                "skipped_count": {
                    "type": "integer"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sync.MetaSyncStep"
                    }
                },
                "sync_mode": {
                    "type": "string"
                },
                "sync_scope": {
                    "type": "string"
                },
                "total_records": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_count": {
                    "type": "integer"
                }
            }
        },
        "sync.MetaSyncStep": {
            "type": "object",
            "properties": {
                "batch": {
                    "$ref": "#/definitions/sync.MetaSyncBatch"
                },
                "batch_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "cursor_after": {
                    "type": "string"
                },
                "cursor_before": {
                    "type": "string"
                },
                "duration_ms": {
                    "type": "integer"
                },
                "endpoint": {
                    "type": "string"
                },
                "error_code": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "failed_count": {
                    "type": "integer"
                },
                "finished_at": {
                    "type": "string"
                },
                "has_next": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "inserted_count": {
                    "type": "integer"
                },
                "metadata": {
                    "type": "object"
                },
                "request_count": {
                    "type": "integer"
                },
                "skipped_count": {
                    "type": "integer"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "sync_type": {
                    "type": "string"
                },
                "total_records": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_count": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Tuliskan 'Bearer ' diikuti dengan token JWT Anda.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8888",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Ads Backend API",
	Description:      "ERP Ready Backend for Meta Ads & Business Management",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
