// Code generated by mockery v2.53.6. DO NOT EDIT.

package role

import (
	dto "github.com/alex/ads_backend/internal/core/role/dto"
	mock "github.com/stretchr/testify/mock"

	permission "github.com/alex/ads_backend/internal/core/permission"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// AssignPermissions provides a mock function with given fields: role, permissions
func (_m *MockRepository) AssignPermissions(role *Role, permissions []permission.Permission) error {
	ret := _m.Called(role, permissions)

	if len(ret) == 0 {
		panic("no return value specified for AssignPermissions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*Role, []permission.Permission) error); ok {
		r0 = rf(role, permissions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: role
func (_m *MockRepository) Create(role *Role) error {
	ret := _m.Called(role)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*Role) error); ok {
		r0 = rf(role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *MockRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: filter
func (_m *MockRepository) FindAll(filter dto.RoleFilter) ([]Role, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []Role
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(dto.RoleFilter) ([]Role, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(dto.RoleFilter) []Role); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Role)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.RoleFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(dto.RoleFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: id
func (_m *MockRepository) FindByID(id uint) (*Role, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *Role
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*Role, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *Role); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Role)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIDs provides a mock function with given fields: ids
func (_m *MockRepository) FindByIDs(ids []uint) ([]Role, error) {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []Role
	var r1 error
	if rf, ok := ret.Get(0).(func([]uint) ([]Role, error)); ok {
		return rf(ids)
	}
	if rf, ok := ret.Get(0).(func([]uint) []Role); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Role)
		}
	}

	if rf, ok := ret.Get(1).(func([]uint) error); ok {
		r1 = rf(ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: role
func (_m *MockRepository) Update(role *Role) error {
	ret := _m.Called(role)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*Role) error); ok {
		r0 = rf(role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
