// Code generated by mockery v2.53.6. DO NOT EDIT.

package ads

import mock "github.com/stretchr/testify/mock"

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// FindAdDashboard provides a mock function with given fields: filter
func (_m *MockRepository) FindAdDashboard(filter AdFilter) ([]adDashboardScan, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAdDashboard")
	}

	var r0 []adDashboardScan
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(AdFilter) ([]adDashboardScan, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(AdFilter) []adDashboardScan); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]adDashboardScan)
		}
	}

	if rf, ok := ret.Get(1).(func(AdFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(AdFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindAll provides a mock function with given fields: filter
func (_m *MockRepository) FindAll(filter AdFilter) ([]MetaAd, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []MetaAd
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(AdFilter) ([]MetaAd, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(AdFilter) []MetaAd); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MetaAd)
		}
	}

	if rf, ok := ret.Get(1).(func(AdFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(AdFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindCreativeRawPayload provides a mock function with given fields: creativeID
func (_m *MockRepository) FindCreativeRawPayload(creativeID string) (string, error) {
	ret := _m.Called(creativeID)

	if len(ret) == 0 {
		panic("no return value specified for FindCreativeRawPayload")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(creativeID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(creativeID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(creativeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: ad
func (_m *MockRepository) Upsert(ad *MetaAd) error {
	ret := _m.Called(ad)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*MetaAd) error); ok {
		r0 = rf(ad)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertBatch provides a mock function with given fields: ads
func (_m *MockRepository) UpsertBatch(ads []MetaAd) error {
	ret := _m.Called(ads)

	if len(ret) == 0 {
		panic("no return value specified for UpsertBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]MetaAd) error); ok {
		r0 = rf(ads)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
