// Code generated by mockery v2.53.6. DO NOT EDIT.

package ads

import (
	dto "github.com/alex/ads_backend/internal/meta/ads/dto"
	mock "github.com/stretchr/testify/mock"

	response "github.com/alex/ads_backend/pkg/response"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// GetAds provides a mock function with given fields: filter
func (_m *MockService) GetAds(filter AdFilter) ([]dto.AdResponse, *response.PaginationMeta, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAds")
	}

	var r0 []dto.AdResponse
	var r1 *response.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(AdFilter) ([]dto.AdResponse, *response.PaginationMeta, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(AdFilter) []dto.AdResponse); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.AdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(AdFilter) *response.PaginationMeta); ok {
		r1 = rf(filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.PaginationMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(AdFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetCreative provides a mock function with given fields: creativeID, fields
func (_m *MockService) GetCreative(creativeID string, fields string) (*dto.CreativeResponse, error) {
	ret := _m.Called(creativeID, fields)

	if len(ret) == 0 {
		panic("no return value specified for GetCreative")
	}

	var r0 *dto.CreativeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*dto.CreativeResponse, error)); ok {
		return rf(creativeID, fields)
	}
	if rf, ok := ret.Get(0).(func(string, string) *dto.CreativeResponse); ok {
		r0 = rf(creativeID, fields)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CreativeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(creativeID, fields)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SyncAds provides a mock function with given fields: adAccountID
func (_m *MockService) SyncAds(adAccountID string) (int, error) {
	ret := _m.Called(adAccountID)

	if len(ret) == 0 {
		panic("no return value specified for SyncAds")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(adAccountID)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(adAccountID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(adAccountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SyncAdsWithList provides a mock function with given fields: adAccountID
func (_m *MockService) SyncAdsWithList(adAccountID string) (int, []MetaAd, error) {
	ret := _m.Called(adAccountID)

	if len(ret) == 0 {
		panic("no return value specified for SyncAdsWithList")
	}

	var r0 int
	var r1 []MetaAd
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (int, []MetaAd, error)); ok {
		return rf(adAccountID)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(adAccountID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) []MetaAd); ok {
		r1 = rf(adAccountID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]MetaAd)
		}
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(adAccountID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
